# Generated by Django 4.1 on 2022-08-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('category', '0002_alter_category_name'),
        ('ad', '0002_remove_user_location_alter_ad_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad',
            new_name='Ads',
        ),
    ]
