# Generated by Django 4.1 on 2022-08-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('category', '0002_alter_category_name'),
        ('ad', '0003_rename_ad_ads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Ad',
        ),
    ]
